### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED on classification

### ISSUE THREAD

**Issue by TheRealMarVin** [yanx27/Pointnet_Pointnet2_pytorch#49]
I have the following error when trying to train classification. I tried to reduce batch size and number of points and I always have the issue.

Traceback (most recent call last):
  File "train_cls.py", line 209, in <module>
    main(args)
  File "train_cls.py", line 171, in main
    loss.backward()
  File "...site-packages\torch\tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "...site-packages\torch\autograd\__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

My conda environment is:
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2019.11.27                    0    anaconda
certifi                   2019.11.28               py37_0    anaconda
cffi                      1.13.2           py37h7a1dbc1_0
cudatoolkit               10.1.243             h74a9793_0
cudnn                     7.6.5                cuda10.1_0    anaconda
freetype                  2.9.1                ha9979f8_1
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2019.4                      245
jpeg                      9b               vc14h4d7706e_1  [vc14]  anaconda
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.1.0                h56a325e_0
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
ninja                     1.9.0            py37h74a9793_0
numpy                     1.18.1           py37h93ca92e_0
numpy-base                1.18.1           py37hc3f5095_1
olefile                   0.46                     py37_0
openssl                   1.1.1                he774522_0    anaconda
pillow                    5.2.0            py37h08bbbbd_0
pip                       20.0.2                   py37_0
pycparser                 2.19                     py37_0
python                    3.7.6                h60c2a47_2
pytorch                   1.4.0           py3.7_cuda101_cudnn7_0    pytorch
setuptools                45.1.0                   py37_0
six                       1.14.0                   py37_0
sqlite                    3.30.1               he774522_0
tk                        8.6.7            vc14hb68737d_1  [vc14]  anaconda
torchvision               0.5.0                py37_cu101    pytorch
tqdm                      4.42.0                     py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.33.6                   py37_0
wincertstore              0.2                      py37_0
xz                        5.2.4                h2fa13f4_4
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  anaconda
zstd                      1.3.7                h508b16e_0

Any idea?

**Comment by TheRealMarVin** [comment]
changed normalisation to p="nuc" in this method and it worked

**Comment by sharechanxd** [comment]
> changed normalisation to p="nuc" in this method and it worked

I am sorry I have the same problem, how did you fic it?

**Comment by TheRealMarVin** [comment]
in pointnet.py line 141. I changed for this line: v = torch.norm(u, dim=(1, 2), p="nuc")
I am not sure of the precise effect of using "nuc", but it gave decent results for me

**Comment by mazhenyuwin** [comment]
Hi, I meet the same problem with the same cudnn and pytorch version. The error did not change after changing pointnet.py line 140 to: loss = torch.mean(torch.norm(torch.bmm(trans, trans.transpose(2, 1) - I), dim=(1, 2),p="nuc")) in current version. Have u solved by doing this?

**Comment by passion3394** [comment]
the best solution is to compile torch from source, it can solve all this kind of problems.

**Comment by mazhenyuwin** [comment]
> the best solution is to compile torch from source, it can solve all this kind of problems.

Thank you. I solved it using torch 1.3.1 cudnn 7.6.5. cuda 10.0
